version: 2

builds:
  - main: ./main.go
    binary: kudasai
    ldflags:
      - -s -w -X github.com/vibaiher/kudasai/pkg/kudasai.Version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "kudasai_{{ .Os }}_{{ .Arch }}"
