name: Main

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...

  test-acceptance:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: Install clitest
      run: |
        curl -sOL https://raw.githubusercontent.com/aureliojargas/clitest/master/clitest
        chmod +x clitest
    - name: Install kudasai binary
      run: go install
    - name: Run acceptance test
      run: ./clitest examples/**
